import { PERMISSIONS, type PermissionKey } from './permission-keys';
import { ROLE_KEYS, type RoleKey } from '../roles/role-keys';

const P = PERMISSIONS;

/**
 * Default permission set for each system role, derived from the approved permission matrix
 * (Architecture Plan §3 and §19.2). Scope restrictions (own / team / public-only) are applied
 * by the services, not by these keys — a Developer with `task:work` can still only work on
 * tasks assigned to them.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, readonly PermissionKey[]> = {
  [ROLE_KEYS.SUPER_ADMIN]: Object.values(P),

  [ROLE_KEYS.PROJECT_MANAGER]: [
    P.PROJECT_READ,
    P.PROJECT_MANAGE,
    P.CONTRACT_READ,
    P.CONTRACT_MANAGE,
    P.CONTRACT_ADJUST_HOURS,
    P.MILESTONE_MANAGE,
    P.CHANGE_REQUEST_READ,
    P.CHANGE_REQUEST_RAISE,
    P.CHANGE_REQUEST_MANAGE,
    P.TASK_READ,
    // The organization-wide task reader, alongside `report:read-all`, which this role already
    // holds for the same reason: a project manager answers for work they are not a member of.
    // A team lead is deliberately not given it — their width is the teams they lead and the
    // projects they are on, which the scope resolves for them without a permission.
    P.TASK_READ_ALL,
    P.TASK_CREATE,
    P.TASK_ASSIGN,
    P.TASK_WORK,
    P.TASK_REVIEW,
    P.TASK_OVERRIDE_CHECKS,
    P.TASK_CANCEL,
    P.COMMENT_INTERNAL,
    P.CLIENT_UPDATE_PUBLISH,
    P.APPROVAL_MANAGE,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_TRIAGE,
    P.TICKET_ACCEPT,
    P.TICKET_ESCALATE,
    P.TICKET_REASSIGN,
    P.TICKET_RESOLVE,
    P.TICKET_REPLY_PUBLIC,
    P.SUPPORT_ROUTING_MANAGE,
    P.PRODUCT_READ,
    P.PRODUCT_MANAGE,
    P.SUPPORT_TIER_MANAGE,
    P.SLA_MANAGE,
    P.QA_ASSIGN,
    // Signing off a deployment they watched go out is the ordinary case for a release manager,
    // and `testing-assignment-workflow.ts` says so where it declines to make `verifyLive`
    // assignee-only. Without this the permission was the tester's alone and the rule was a
    // sentence nobody could act on.
    P.QA_VERIFY_LIVE,
    P.TEST_ACCOUNT_MANAGE,
    P.RELEASE_MANAGE,
    P.RELEASE_APPROVE,
    P.RELEASE_PUBLISH,
    P.GITHUB_MANAGE,
    P.PROBLEM_READ,
    P.PROBLEM_MANAGE,
    P.PROBLEM_ADD_PREVENTIVE_TEST,
    P.INCIDENT_READ,
    P.INCIDENT_MANAGE,
    P.INCIDENT_APPROVE_EMERGENCY_FIX,
    P.CALL_INITIATE,
    P.CALL_READ_INTERNAL,
    P.CALL_PLAY_RECORDING,
    P.IVR_MANAGE,
    P.CONVERSATION_PARTICIPATE,
    P.CONVERSATION_CALL,
    P.CONVERSATION_RECORDING_PLAY,
    P.CONVERSATION_SETTINGS_MANAGE,
    P.REPORT_READ_OWN,
    P.REPORT_READ_TEAM,
    P.REPORT_READ_ALL,
    P.REPORT_EXPORT,
    P.AUDIT_LOG_READ,
    P.INTEGRATION_READ,
    P.REPOSITORY_READ,
    P.REPOSITORY_MANAGE,
    P.RELEASE_NOTE_READ,
    P.RELEASE_NOTE_WRITE,
    P.RELEASE_NOTE_APPROVE,
    P.RELEASE_NOTE_PUBLISH,
    P.INVOICE_READ,
    P.INVOICE_WRITE,
    P.INVOICE_ISSUE,
    // Cancel, not void: withdrawing a draft nobody was sent is an ordinary correction and belongs
    // to whoever may raise the invoice. Void keeps a used number against a document a client
    // relied on, and stays with the administrator.
    P.INVOICE_CANCEL,
    P.PAYMENT_READ,
    P.PAYMENT_RECORD,
    P.AI_SUMMARY_READ,
    P.AI_SUMMARY_GENERATE,
    P.AI_SUMMARY_APPROVE,
  ],

  [ROLE_KEYS.TEAM_LEAD]: [
    P.PROJECT_READ,
    P.PROJECT_MANAGE,
    P.CONTRACT_READ,
    P.MILESTONE_MANAGE,
    P.CHANGE_REQUEST_READ,
    P.CHANGE_REQUEST_RAISE,
    P.CHANGE_REQUEST_MANAGE,
    P.TASK_READ,
    P.TASK_CREATE,
    P.TASK_ASSIGN,
    P.TASK_WORK,
    P.TASK_REVIEW,
    P.TASK_OVERRIDE_CHECKS,
    P.TASK_CANCEL,
    P.COMMENT_INTERNAL,
    P.CLIENT_UPDATE_PUBLISH,
    P.APPROVAL_MANAGE,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_TRIAGE,
    P.TICKET_ACCEPT,
    P.TICKET_ESCALATE,
    P.TICKET_REASSIGN,
    P.TICKET_RESOLVE,
    P.TICKET_REPLY_PUBLIC,
    P.SUPPORT_ROUTING_MANAGE,
    P.PRODUCT_READ,
    P.QA_ASSIGN,
    P.RELEASE_MANAGE,
    P.RELEASE_APPROVE,
    P.PROBLEM_READ,
    P.PROBLEM_MANAGE,
    P.PROBLEM_ADD_PREVENTIVE_TEST,
    P.RCA_SUBMIT,
    P.INCIDENT_READ,
    P.INCIDENT_MANAGE,
    P.INCIDENT_APPROVE_EMERGENCY_FIX,
    P.CALL_INITIATE,
    P.CALL_READ_INTERNAL,
    P.CALL_PLAY_RECORDING,
    P.CONVERSATION_PARTICIPATE,
    P.CONVERSATION_CALL,
    P.CONVERSATION_RECORDING_PLAY,
    P.REPORT_READ_OWN,
    P.REPORT_READ_TEAM,
    P.REPORT_EXPORT,
    P.INTEGRATION_READ,
    P.REPOSITORY_READ,
    P.RELEASE_NOTE_READ,
    P.RELEASE_NOTE_WRITE,
    P.RELEASE_NOTE_APPROVE,
    P.AI_SUMMARY_READ,
    P.AI_SUMMARY_GENERATE,
    P.AI_SUMMARY_APPROVE,
  ],

  [ROLE_KEYS.DEVELOPER]: [
    P.PROJECT_READ,
    P.CHANGE_REQUEST_READ,
    P.TASK_READ,
    P.TASK_CREATE,
    P.TASK_WORK,
    P.COMMENT_INTERNAL,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_ACCEPT,
    P.TICKET_ESCALATE,
    P.TICKET_REPLY_PUBLIC,
    P.QA_ASSIGN,
    P.PROBLEM_READ,
    P.PROBLEM_SUGGEST_DUPLICATE,
    P.RCA_SUBMIT,
    P.INCIDENT_READ,
    P.CALL_INITIATE,
    P.CALL_READ_INTERNAL,
    // Participate and call, but no recording playback: having been on a call is not a reason to
    // be able to listen to it again, which is the whole point of keeping the two separate.
    P.CONVERSATION_PARTICIPATE,
    P.CONVERSATION_CALL,
    P.REPORT_READ_OWN,
    P.REPOSITORY_READ,
    P.RELEASE_NOTE_READ,
    P.AI_SUMMARY_READ,
  ],

  [ROLE_KEYS.TESTER]: [
    P.PROJECT_READ,
    P.CHANGE_REQUEST_READ,
    P.TASK_READ,
    P.TASK_CREATE,
    P.TASK_WORK,
    P.COMMENT_INTERNAL,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_REPLY_PUBLIC,
    P.QA_RECORD_RESULT,
    P.QA_VERIFY_LIVE,
    P.TEST_CREDENTIAL_REVEAL,
    // Deliberately not `release:approve`. A QA_LEAD approver role exists and is what a project
    // names when it wants QA's signature on a release; granting the permission to every tester
    // by default made that role decorative and let anyone who records results sign a release off.
    // A tenant that wants it back grants it on a custom role, which this default does not touch.
    P.PROBLEM_READ,
    P.PROBLEM_SUGGEST_DUPLICATE,
    // The approved permission matrix gives QA exactly one write on a problem: the preventive test.
    P.PROBLEM_ADD_PREVENTIVE_TEST,
    P.INCIDENT_READ,
    P.CONVERSATION_PARTICIPATE,
    P.CONVERSATION_CALL,
    P.REPORT_READ_OWN,
    P.REPOSITORY_READ,
    P.RELEASE_NOTE_READ,
    P.AI_SUMMARY_READ,
  ],

  [ROLE_KEYS.SUPPORT_EXECUTIVE]: [
    P.PROJECT_READ,
    P.CONTRACT_READ,
    P.CHANGE_REQUEST_READ,
    P.CHANGE_REQUEST_RAISE,
    P.TASK_READ,
    P.TASK_CREATE,
    P.TASK_ASSIGN,
    P.TASK_WORK,
    P.COMMENT_INTERNAL,
    P.CLIENT_UPDATE_PUBLISH,
    P.APPROVAL_MANAGE,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_TRIAGE,
    P.TICKET_ACCEPT,
    P.TICKET_ESCALATE,
    P.TICKET_REASSIGN,
    P.TICKET_RESOLVE,
    P.TICKET_REPLY_PUBLIC,
    P.PRODUCT_READ,
    P.PROBLEM_READ,
    P.PROBLEM_MANAGE,
    P.INCIDENT_READ,
    P.INCIDENT_MANAGE,
    P.CALL_INITIATE,
    P.CALL_READ_INTERNAL,
    P.CONVERSATION_PARTICIPATE,
    P.CONVERSATION_CALL,
    P.REPORT_READ_OWN,
  ],

  // The permission is not the gate — project membership is. Withholding it from an internal
  // employee who is a legitimate project member would break them silently.
  [ROLE_KEYS.INTERNAL_EMPLOYEE]: [
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_REPLY_PUBLIC,
    P.CONVERSATION_PARTICIPATE,
  ],

  [ROLE_KEYS.CLIENT_ADMIN]: [
    P.USER_MANAGE,
    P.PROJECT_READ,
    P.CONTRACT_READ,
    P.CHANGE_REQUEST_READ,
    P.CHANGE_REQUEST_RAISE,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_REPLY_PUBLIC,
    P.APPROVAL_DECIDE,
    P.UAT_DECIDE,
    P.REPORT_READ_OWN,
    P.REPORT_EXPORT,
  ],

  [ROLE_KEYS.CLIENT_EMPLOYEE]: [
    P.PROJECT_READ,
    P.CHANGE_REQUEST_READ,
    P.TICKET_RAISE,
    P.TICKET_READ,
    P.TICKET_REPLY_PUBLIC,
  ],
};

export function getDefaultPermissionsForRole(roleKey: RoleKey): readonly PermissionKey[] {
  return DEFAULT_ROLE_PERMISSIONS[roleKey];
}
