import { CLIENT_UPDATE_STATUS, PRIORITY, TASK_STATUS, VISIBILITY } from '@ashniva/types';

import type { TaskSeed } from './seed-tasks-data';

const S = TASK_STATUS;
const P = PRIORITY;
const V = VISIBILITY;
const U = CLIENT_UPDATE_STATUS;

export const ACME_POS_TASKS: readonly TaskSeed[] = [
  {
    number: 1,
    project: 'acmePos',
    title: 'Daily closing report totals mismatch',
    description:
      'Cash + card totals on the closing report differ from the register by the refund amount.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.HIGH,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 0,
    ageDays: 3,
    lastChangeDaysAgo: 0,
    estimateMinutes: 240,
    module: 'Reports',
    clientVisible: true,
    lastNote: 'Verified on staging with three stores’ closing data.',
    workLogs: [
      {
        user: 'developer',
        dayOffset: -1,
        minutes: 150,
        summary: 'Traced refunds being excluded from the card total',
        gitRef: 'fix/closing-totals',
      },
      {
        user: 'developer',
        dayOffset: 0,
        minutes: 120,
        summary: 'Fixed refund handling and added report tests',
        gitRef: 'PR #142',
      },
    ],
    comments: [
      {
        author: 'tester',
        visibility: V.INTERNAL,
        body: 'Checked with store 7 and store 12 closing data — totals match now.',
        dayOffset: 0,
      },
    ],
    clientUpdate: {
      status: U.PUBLISHED,
      body: 'The daily closing report now includes refunds correctly. Totals match the register.',
    },
  },
  {
    number: 2,
    project: 'acmePos',
    title: 'Barcode scanner support for the new HID model',
    description: 'Store counters received a new scanner model that is not detected by the POS.',
    category: 'Development',
    status: S.IN_PROGRESS,
    priority: P.HIGH,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 0,
    ageDays: 2,
    lastChangeDaysAgo: 1,
    estimateMinutes: 480,
    module: 'Hardware',
    workLogs: [
      {
        user: 'developer',
        dayOffset: -1,
        minutes: 180,
        summary: 'Reproduced with the sample device; identified vendor id handling',
      },
      {
        user: 'developer',
        dayOffset: 0,
        minutes: 60,
        summary: 'Implementing HID keyboard-wedge fallback',
      },
    ],
    comments: [
      {
        author: 'lead',
        visibility: V.INTERNAL,
        body: 'The vendor manual is in the shared drive under Acme/hardware.',
        dayOffset: -1,
      },
    ],
  },
  {
    number: 3,
    project: 'acmePos',
    title: 'GST invoice PDF layout',
    description: 'Invoice PDF must show HSN codes and tax split per line.',
    category: 'Development',
    status: S.IN_REVIEW,
    priority: P.MEDIUM,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 1,
    ageDays: 4,
    lastChangeDaysAgo: 0,
    estimateMinutes: 360,
    module: 'Billing',
    clientVisible: true,
    workLogs: [
      { user: 'developer', dayOffset: -2, minutes: 200, summary: 'Built the new PDF template' },
      {
        user: 'developer',
        dayOffset: 0,
        minutes: 240,
        summary: 'Tax split per line and rounding; submitted for testing',
        gitRef: 'PR #145',
      },
    ],
  },
  {
    number: 4,
    project: 'acmePos',
    title: 'Discount rules engine',
    description: 'Combine item, bill and coupon discounts with correct precedence.',
    category: 'Development',
    status: S.RETURNED_TO_DEV,
    priority: P.HIGH,
    createdBy: 'pm',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: 1,
    ageDays: 6,
    lastChangeDaysAgo: 1,
    estimateMinutes: 600,
    module: 'Billing',
    lastNote: 'Rejected: coupon discount is applied before the bill discount; see comment.',
    workLogs: [
      {
        user: 'developer2',
        dayOffset: -3,
        minutes: 300,
        summary: 'Rule precedence implementation',
      },
      { user: 'developer2', dayOffset: -2, minutes: 120, summary: 'Unit tests and submission' },
    ],
    comments: [
      {
        author: 'tester',
        visibility: V.INTERNAL,
        body: 'Bill discount of 10% on a bill with a ₹100 coupon gives ₹90 less instead of ₹100 less. Precedence is reversed.',
        dayOffset: -1,
      },
    ],
  },
  {
    number: 5,
    project: 'acmePos',
    title: 'Offline mode sync conflicts',
    description:
      'When two counters edit the same stock item offline, the later sync silently wins.',
    category: 'Development',
    status: S.BLOCKED,
    priority: P.MEDIUM,
    createdBy: 'lead',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: -2,
    ageDays: 9,
    lastChangeDaysAgo: 2,
    estimateMinutes: 720,
    module: 'Sync',
    blockedReason: 'Waiting for Acme to share the real conflict cases from store 3.',
    workLogs: [{ user: 'developer2', dayOffset: -4, minutes: 90, summary: 'Analysed sync logs' }],
  },
  {
    number: 6,
    project: 'acmePos',
    title: 'Store manager dashboard widgets',
    description: 'Sales today, top items and low-stock widgets on the manager home screen.',
    category: 'Development',
    status: S.ASSIGNED,
    priority: P.HIGH,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 3,
    ageDays: 1,
    lastChangeDaysAgo: 1,
    estimateMinutes: 480,
    module: 'Dashboard',
    clientVisible: true,
  },
  {
    number: 7,
    project: 'acmePos',
    title: 'Printer settings screen',
    description: 'Let store staff choose the receipt printer and paper width without IT help.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.MEDIUM,
    createdBy: 'lead',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: -1,
    ageDays: 5,
    lastChangeDaysAgo: 1,
    estimateMinutes: 240,
    module: 'Settings',
    clientVisible: true,
    lastNote: 'Approved.',
    workLogs: [
      {
        user: 'developer2',
        dayOffset: -2,
        minutes: 210,
        summary: 'Settings screen and printer detection',
      },
    ],
    clientUpdate: {
      status: U.PENDING,
      body: 'Store staff can now select the receipt printer and paper width from Settings → Printer.',
    },
  },
  {
    number: 8,
    project: 'acmePos',
    title: 'Cash drawer reconciliation',
    description: 'Reconcile opening float, sales and payouts at shift end.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.MEDIUM,
    createdBy: 'pm',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: -3,
    ageDays: 10,
    lastChangeDaysAgo: 3,
    estimateMinutes: 480,
    module: 'Cash',
    clientVisible: true,
    lastNote: 'Approved after retest.',
    workLogs: [
      { user: 'developer', dayOffset: -5, minutes: 300, summary: 'Reconciliation screen' },
      { user: 'developer', dayOffset: -4, minutes: 180, summary: 'Payout handling and tests' },
    ],
    clientUpdate: {
      status: U.PUBLISHED,
      body: 'Shift-end cash drawer reconciliation is available under Cash → Reconcile.',
    },
  },
];
