import { PRIORITY, TASK_STATUS } from '@ashniva/types';

import type { TaskSeed } from './seed-tasks-data';

const S = TASK_STATUS;
const P = PRIORITY;

export const INTERNAL_TASKS: readonly TaskSeed[] = [
  {
    number: 23,
    project: 'groupPayroll',
    title: 'Leave balance carry-forward rule',
    description: 'Carry forward up to 30 days of earned leave at year end.',
    category: 'Development',
    status: S.BLOCKED,
    priority: P.MEDIUM,
    createdBy: 'pm',
    assignee: 'developer',
    reviewer: 'lead',
    due: 14,
    ageDays: 20,
    lastChangeDaysAgo: 10,
    blockedReason: 'Project on hold until the payroll policy is confirmed by GroupHR.',
  },
  {
    number: 24,
    project: 'groupPayroll',
    title: 'Payslip PDF',
    description: 'Monthly payslip PDF with earnings and deductions.',
    category: 'Development',
    status: S.ASSIGNED,
    priority: P.LOW,
    createdBy: 'pm',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 10,
    ageDays: 20,
    lastChangeDaysAgo: 20,
  },
  {
    number: 25,
    project: 'internalDesk',
    title: 'Task board drag and drop',
    description: 'Move cards between columns on the task board.',
    category: 'Development',
    status: S.IN_PROGRESS,
    priority: P.MEDIUM,
    createdBy: 'director',
    assignee: 'lead',
    reviewer: 'director',
    tester: 'tester',
    due: 4,
    ageDays: 3,
    lastChangeDaysAgo: 1,
    estimateMinutes: 480,
    workLogs: [{ user: 'lead', dayOffset: -1, minutes: 120, summary: 'Drag-and-drop prototype' }],
  },
  {
    number: 26,
    project: 'internalDesk',
    title: 'Audit history filters',
    description: 'Filter the audit history by type, person and date.',
    category: 'Development',
    status: S.IN_REVIEW,
    priority: P.MEDIUM,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 2,
    ageDays: 3,
    lastChangeDaysAgo: 0,
    estimateMinutes: 240,
    workLogs: [
      { user: 'developer', dayOffset: -1, minutes: 90, summary: 'Filter chips and query params' },
      { user: 'developer', dayOffset: 0, minutes: 30, summary: 'Submitted for review' },
    ],
  },
  {
    number: 27,
    project: 'internalDesk',
    title: 'Client portal empty states',
    description: 'Friendly empty states for projects, tickets and updates.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.LOW,
    createdBy: 'lead',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: -1,
    ageDays: 4,
    lastChangeDaysAgo: 1,
    estimateMinutes: 120,
    lastNote: 'Approved.',
    workLogs: [
      { user: 'developer2', dayOffset: -2, minutes: 100, summary: 'Empty-state components' },
    ],
  },
  {
    number: 28,
    project: 'internalDesk',
    title: 'Release notes template',
    description: 'A template for the release notes we send to clients.',
    category: 'Documentation',
    status: S.DRAFT,
    priority: P.LOW,
    createdBy: 'director',
    ageDays: 1,
    lastChangeDaysAgo: 1,
  },
  {
    number: 29,
    project: 'acmeStore',
    title: 'Test plan: UPI checkout',
    description: 'Write and execute the test plan for the UPI checkout release.',
    category: 'Testing',
    status: S.IN_PROGRESS,
    priority: P.MEDIUM,
    createdBy: 'lead',
    assignee: 'tester',
    reviewer: 'lead',
    due: 1,
    ageDays: 2,
    lastChangeDaysAgo: 0,
    estimateMinutes: 180,
    workLogs: [
      {
        user: 'tester',
        dayOffset: 0,
        minutes: 75,
        summary: 'Test cases for success, failure and timeout flows',
      },
    ],
  },
];
