import { CLIENT_UPDATE_STATUS, PRIORITY, TASK_STATUS } from '@ashniva/types';

import type { TaskSeed } from './seed-tasks-data';

const S = TASK_STATUS;
const P = PRIORITY;
const U = CLIENT_UPDATE_STATUS;

export const ZENITH_TASKS: readonly TaskSeed[] = [
  {
    number: 18,
    project: 'zenithFleet',
    title: 'Live map: vehicle markers flicker',
    description: 'Markers disappear and reappear every refresh on the dispatch map.',
    category: 'Development',
    status: S.IN_PROGRESS,
    priority: P.CRITICAL,
    createdBy: 'support',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: 0,
    ageDays: 1,
    lastChangeDaysAgo: 0,
    estimateMinutes: 180,
    module: 'Live map',
    clientVisible: true,
    workLogs: [
      {
        user: 'developer2',
        dayOffset: 0,
        minutes: 90,
        summary: 'Found the marker layer being recreated on every poll',
      },
    ],
  },
  {
    number: 19,
    project: 'zenithFleet',
    title: 'Trip report export to Excel',
    description: 'Export the trip report with the same columns as the screen.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.MEDIUM,
    createdBy: 'support',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: 0,
    ageDays: 4,
    lastChangeDaysAgo: 0,
    estimateMinutes: 240,
    module: 'Reports',
    clientVisible: true,
    lastNote: 'Approved.',
    workLogs: [
      { user: 'developer2', dayOffset: -2, minutes: 180, summary: 'Excel export service' },
      {
        user: 'developer2',
        dayOffset: 0,
        minutes: 60,
        summary: 'Column formatting fixes from testing',
      },
    ],
    clientUpdate: {
      status: U.PUBLISHED,
      body: 'Trip reports can now be exported to Excel from Reports → Trips → Export.',
    },
  },
  {
    number: 20,
    project: 'zenithFleet',
    title: 'Driver app: login timeout',
    description: 'Drivers are logged out after 10 minutes in the field.',
    category: 'Development',
    status: S.IN_REVIEW,
    priority: P.HIGH,
    createdBy: 'lead',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: 1,
    ageDays: 3,
    lastChangeDaysAgo: 0,
    estimateMinutes: 240,
    module: 'Driver app',
    workLogs: [
      {
        user: 'developer2',
        dayOffset: -1,
        minutes: 150,
        summary: 'Refresh token handling in the driver app',
      },
      {
        user: 'developer2',
        dayOffset: 0,
        minutes: 45,
        summary: 'Submitted for testing',
        gitRef: 'PR #31',
      },
    ],
  },
  {
    number: 21,
    project: 'zenithFleet',
    title: 'Geofence alerts for depots',
    description: 'Alert dispatch when a vehicle enters or leaves a depot.',
    category: 'Development',
    status: S.ASSIGNED,
    priority: P.MEDIUM,
    createdBy: 'pm',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: 5,
    ageDays: 1,
    lastChangeDaysAgo: 1,
    estimateMinutes: 480,
    module: 'Alerts',
    clientVisible: true,
  },
  {
    number: 22,
    project: 'zenithFleet',
    title: 'Fuel report rounding',
    description: 'Litres are rounded to whole numbers in the fuel report.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.LOW,
    createdBy: 'support',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: -1,
    ageDays: 3,
    lastChangeDaysAgo: 1,
    estimateMinutes: 60,
    module: 'Reports',
    clientVisible: true,
    lastNote: 'Approved.',
    workLogs: [
      {
        user: 'developer2',
        dayOffset: -1,
        minutes: 40,
        summary: 'Two-decimal rounding in the fuel report',
      },
    ],
    clientUpdate: {
      status: U.PENDING,
      body: 'Fuel quantities in the fuel report now show two decimals.',
    },
  },
];
