import { PRIORITY, TASK_STATUS, VISIBILITY } from '@ashniva/types';

import type { TaskSeed } from './seed-tasks-data';

const S = TASK_STATUS;
const P = PRIORITY;
const V = VISIBILITY;

export const ACME_MORE_TASKS: readonly TaskSeed[] = [
  {
    number: 9,
    project: 'acmePos',
    title: 'Migrate reports to the old reporting API',
    description: 'Superseded by the new reports service.',
    category: 'Development',
    status: S.CANCELLED,
    priority: P.LOW,
    createdBy: 'pm',
    assignee: 'developer',
    ageDays: 12,
    lastChangeDaysAgo: 8,
    lastNote: 'Cancelled — superseded by the new reports service.',
  },
  {
    number: 10,
    project: 'acmePos',
    title: 'Receipt footer text',
    description: 'Footer must show the new registered address of each store.',
    category: 'Development',
    status: S.REOPENED,
    priority: P.MEDIUM,
    createdBy: 'pm',
    assignee: 'developer2',
    reviewer: 'lead',
    tester: 'tester',
    due: 2,
    ageDays: 8,
    lastChangeDaysAgo: 1,
    module: 'Billing',
    clientVisible: true,
    lastNote: 'Reopened: client reports the footer still shows the old address in store 4.',
    workLogs: [
      { user: 'developer2', dayOffset: -6, minutes: 60, summary: 'Updated footer template' },
    ],
    comments: [
      {
        author: 'clientEmployee',
        visibility: V.CLIENT,
        body: 'Store 4 receipts still print the old address.',
        dayOffset: -1,
      },
    ],
  },
  {
    number: 11,
    project: 'acmePos',
    title: 'Loyalty points on POS receipts',
    description: 'Print the points earned and balance on every receipt.',
    category: 'Development',
    status: S.DRAFT,
    priority: P.LOW,
    createdBy: 'lead',
    ageDays: 0,
    lastChangeDaysAgo: 0,
    module: 'Billing',
  },
  {
    number: 12,
    project: 'acmePos',
    title: 'Weekly sync with Acme operations',
    description: 'Agenda: closing report fix, scanner rollout, discount rules.',
    category: 'Client Meeting',
    status: S.COMPLETED,
    priority: P.MEDIUM,
    createdBy: 'pm',
    assignee: 'lead',
    reviewer: 'pm',
    due: 0,
    ageDays: 1,
    lastChangeDaysAgo: 0,
    lastNote: 'Minutes shared with the client.',
    workLogs: [
      { user: 'lead', dayOffset: 0, minutes: 45, summary: 'Weekly sync call and minutes' },
    ],
  },
  {
    number: 13,
    project: 'acmePos',
    title: 'Performance: item search under 200 ms',
    description: 'Item search on the billing screen takes 1–2 s on large catalogues.',
    category: 'Development',
    status: S.IN_PROGRESS,
    priority: P.HIGH,
    createdBy: 'lead',
    assignee: 'lead',
    reviewer: 'pm',
    tester: 'tester',
    due: 2,
    ageDays: 2,
    lastChangeDaysAgo: 0,
    estimateMinutes: 360,
    module: 'Billing',
    workLogs: [
      { user: 'lead', dayOffset: 0, minutes: 90, summary: 'Added trigram index and query rewrite' },
    ],
  },
  {
    number: 14,
    project: 'acmeStore',
    title: 'Checkout: UPI payment option',
    description: 'Add UPI as a payment method at checkout.',
    category: 'Development',
    status: S.IN_REVIEW,
    priority: P.HIGH,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: -1,
    ageDays: 6,
    lastChangeDaysAgo: 1,
    estimateMinutes: 480,
    module: 'Checkout',
    clientVisible: true,
    workLogs: [
      { user: 'developer', dayOffset: -3, minutes: 240, summary: 'Payment gateway integration' },
      {
        user: 'developer',
        dayOffset: -1,
        minutes: 180,
        summary: 'Checkout UI and error handling; submitted',
        gitRef: 'PR #88',
      },
    ],
  },
  {
    number: 15,
    project: 'acmeStore',
    title: 'Loyalty tier email templates',
    description: 'Silver / gold / platinum welcome emails.',
    category: 'Development',
    status: S.ASSIGNED,
    priority: P.MEDIUM,
    createdBy: 'pm',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: -3,
    ageDays: 7,
    lastChangeDaysAgo: 7,
    estimateMinutes: 180,
    module: 'Loyalty',
  },
  {
    number: 16,
    project: 'acmeStore',
    title: 'Product image CDN caching',
    description: 'Serve product images through the CDN with long cache headers.',
    category: 'Development',
    status: S.COMPLETED,
    priority: P.LOW,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: -2,
    ageDays: 5,
    lastChangeDaysAgo: 2,
    estimateMinutes: 120,
    module: 'Infrastructure',
    lastNote: 'Approved.',
    workLogs: [
      { user: 'developer', dayOffset: -3, minutes: 100, summary: 'CDN rules and cache headers' },
    ],
  },
  {
    number: 17,
    project: 'acmeStore',
    title: 'Password reset flow',
    description: 'Email-based password reset for store customers.',
    category: 'Development',
    status: S.IN_PROGRESS,
    priority: P.MEDIUM,
    createdBy: 'lead',
    assignee: 'developer',
    reviewer: 'lead',
    tester: 'tester',
    due: 1,
    ageDays: 2,
    lastChangeDaysAgo: 1,
    estimateMinutes: 240,
    module: 'Accounts',
    workLogs: [
      { user: 'developer', dayOffset: -1, minutes: 120, summary: 'Reset token model and email' },
    ],
  },
];
