-- Permissions and their default role grants, as data rather than as a seed.
--
-- Everything here is additive and idempotent:
--
--   * permissions are matched on their stable `key`, never on an id, and an existing row is left
--     exactly as it is — including its description, in case somebody edited one;
--   * grants are matched on (role key, permission key) and inserted only where the pair is
--     missing, so a grant that already exists is untouched and none is ever removed;
--   * only system roles are touched. A custom role is a tenant's own decision about who may do
--     what, and a deployment has no business editing it.
--
-- Safe to run on a fresh database (nothing exists, so all three statements insert) and on an
-- existing one (the rows are there, so only what is missing appears).

-- ---------------------------------------------------------------------------------------------
-- Every permission the application knows about.
-- ---------------------------------------------------------------------------------------------

INSERT INTO permissions (id, key, description, created_at)
SELECT gen_random_uuid(), v.key, v.description, NOW()
FROM (VALUES
  ('organization:manage', 'Create and edit organizations (own group companies and clients)'),
  ('user:manage', 'Invite, edit and deactivate users; assign roles'),
  ('role:manage', 'Edit roles and their permissions'),
  ('branding:manage', 'Change product name, logo and brand colours'),
  ('audit-log:read', 'Read the audit log'),
  ('admin:preview-as', 'Preview the system as another role (read-only, audited)'),
  ('project:read', 'View projects the user is allowed to see'),
  ('project:manage', 'Create and edit projects, milestones and project settings'),
  ('contract:read', 'View contracts and support hours'),
  ('contract:manage', 'Create, edit and archive contracts, documents and payment milestones'),
  ('contract:adjust-hours', 'Add purchased hours and make audited manual hour adjustments'),
  ('milestone:manage', 'Create and edit milestones and deliverables; adjust progress with a reason'),
  ('change-request:read', 'View change requests'),
  ('change-request:raise', 'Raise change requests'),
  ('change-request:manage', 'Review, send to the client, schedule and complete change requests'),
  ('task:read', 'View tasks'),
  ('task:create', 'Create tasks'),
  ('task:assign', 'Assign or reassign tasks to other people'),
  ('task:work', 'Start, block, complete and submit own tasks'),
  ('task:review', 'Approve or reject code review'),
  ('task:override-checks', 'Override failed automated checks with a reason'),
  ('task:cancel', 'Cancel tasks'),
  ('comment:internal', 'Read and write internal comments and estimates'),
  ('client-update:publish', 'Approve and publish client-visible updates'),
  ('approval:manage', 'Prepare, review and publish approval requests to the client'),
  ('approval:decide', 'Approve, request changes or reject on behalf of the client'),
  ('ticket:raise', 'Raise tickets'),
  ('ticket:read', 'View tickets'),
  ('ticket:triage', 'Set type, priority and team on tickets; convert tickets to tasks'),
  ('ticket:accept', 'Accept an auto-assigned ticket and start work on it'),
  ('ticket:escalate', 'Escalate a ticket to the backup developer or senior'),
  ('ticket:reassign', 'Reassign a ticket (reason required)'),
  ('ticket:resolve', 'Resolve and close tickets'),
  ('ticket:reply-public', 'Post client-visible replies on tickets'),
  ('support-routing:manage', 'Configure support ownership, on-call schedules and routing rules'),
  ('product:read', 'View registered products and their support settings'),
  ('product:manage', 'Register products, link projects, and issue machine credentials'),
  ('sla:manage', 'Create and edit SLA policies'),
  ('qa:assign', 'Create testing assignments and select testers'),
  ('qa:record-result', 'Record pass/fail results on testing assignments'),
  ('qa:verify-live', 'Perform live verification after a production release'),
  ('test-account:manage', 'Create and rotate reusable test accounts'),
  ('test-credential:reveal', 'Reveal temporary test credentials (audited)'),
  ('release:manage', 'Create releases, add items, schedule publishing'),
  ('release:approve', 'Approve or reject a release'),
  ('release:publish', 'Publish a release to production or roll it back'),
  ('uat:decide', 'Approve or request changes on client UAT'),
  ('github:manage', 'Connect GitHub and map repositories to projects'),
  ('integration:read', 'View integration connections and their status'),
  ('integration:manage', 'Connect, configure and disconnect integrations'),
  ('repository:read', 'View repositories linked to a project'),
  ('repository:manage', 'Link and unlink repositories on a project'),
  ('release-note:read', 'View release notes'),
  ('release-note:write', 'Create and edit release-note drafts'),
  ('release-note:approve', 'Approve a release-note draft'),
  ('release-note:publish', 'Publish a release note to the client portal'),
  ('communication:manage', 'Change email and WhatsApp settings and send test messages'),
  ('invoice:read', 'View invoices'),
  ('invoice:write', 'Create and edit draft invoices'),
  ('invoice:issue', 'Issue an invoice to a client'),
  ('invoice:void', 'Cancel or void an invoice'),
  ('payment:read', 'View payments recorded against invoices'),
  ('payment:record', 'Record a payment against an invoice'),
  ('ai-summary:read', 'View AI-generated summaries'),
  ('ai-summary:generate', 'Generate AI summaries'),
  ('ai-summary:approve', 'Approve an AI summary for client publication'),
  ('problem:manage', 'Confirm duplicates, create problems, request RCA, close problems'),
  ('problem:suggest-duplicate', 'Suggest that a ticket duplicates another (needs confirmation)'),
  ('rca:submit', 'Submit a root-cause analysis'),
  ('incident:approve-emergency-fix', 'Approve an emergency production fix'),
  ('call:initiate', 'Call a client through the IVR or accept an incoming support call'),
  ('call:read-internal', 'See the internal call history on a ticket and its internal call notes'),
  ('call:play-recording', 'Play a call recording (audited every time)'),
  ('ivr:manage', 'Configure the IVR policy and provider, and view its health'),
  ('report:read-own', 'View own daily reports'),
  ('report:read-team', 'View team and project reports'),
  ('report:read-all', 'View all reports in the organization'),
  ('report:export', 'Export reports to CSV (audited)'),
  ('cost:read', 'View internal costs and profit information')
) AS v(key, description)
ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------------------------
-- The system roles.
--
-- `ux_roles_system_key` (from the first migration) is a partial unique index over `key` where the
-- organization is NULL — exactly the rows this statement inserts — so the conflict target names
-- that predicate. A read-then-write (`WHERE NOT EXISTS`) would look equivalent and is not: two
-- deploys racing each other both see no row, both insert, and the loser dies on the index,
-- leaving a failed entry in `_prisma_migrations` that blocks every later deploy. Letting the
-- database arbitrate costs nothing.
--
-- A tenant's custom role is untouched: it carries an organization, so the index does not cover it
-- and `is_system = false` keeps it out of the grants below.
--
-- `name` is only set on insert: renaming a role is a decision somebody made, and a deployment
-- should not undo it. `audience` is left to the column default, which is what the seed does too.
-- ---------------------------------------------------------------------------------------------

INSERT INTO roles (id, organization_id, key, name, is_system, created_at, updated_at)
SELECT gen_random_uuid(), NULL, v.key, v.name, true, NOW(), NOW()
FROM (VALUES
  ('SUPER_ADMIN', 'Super Admin / Director'),
  ('PROJECT_MANAGER', 'Project Manager'),
  ('TEAM_LEAD', 'Team Lead / Senior Developer'),
  ('DEVELOPER', 'Developer'),
  ('TESTER', 'Tester / QA'),
  ('SUPPORT_EXECUTIVE', 'Support Executive'),
  ('INTERNAL_EMPLOYEE', 'Internal Company Employee'),
  ('CLIENT_ADMIN', 'Client Admin'),
  ('CLIENT_EMPLOYEE', 'Client Employee')
) AS v(key, name)
ON CONFLICT (key) WHERE organization_id IS NULL DO NOTHING;

-- ---------------------------------------------------------------------------------------------
-- The default grants, for system roles only.
--
-- `is_system` and a NULL organization together identify a system role; a tenant's custom role has
-- an organization and `is_system = false`, and is excluded by both conditions.
-- ---------------------------------------------------------------------------------------------

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM (VALUES
  ('SUPER_ADMIN', 'organization:manage'),
  ('SUPER_ADMIN', 'user:manage'),
  ('SUPER_ADMIN', 'role:manage'),
  ('SUPER_ADMIN', 'branding:manage'),
  ('SUPER_ADMIN', 'audit-log:read'),
  ('SUPER_ADMIN', 'admin:preview-as'),
  ('SUPER_ADMIN', 'project:read'),
  ('SUPER_ADMIN', 'project:manage'),
  ('SUPER_ADMIN', 'contract:read'),
  ('SUPER_ADMIN', 'contract:manage'),
  ('SUPER_ADMIN', 'contract:adjust-hours'),
  ('SUPER_ADMIN', 'milestone:manage'),
  ('SUPER_ADMIN', 'change-request:read'),
  ('SUPER_ADMIN', 'change-request:raise'),
  ('SUPER_ADMIN', 'change-request:manage'),
  ('SUPER_ADMIN', 'task:read'),
  ('SUPER_ADMIN', 'task:create'),
  ('SUPER_ADMIN', 'task:assign'),
  ('SUPER_ADMIN', 'task:work'),
  ('SUPER_ADMIN', 'task:review'),
  ('SUPER_ADMIN', 'task:override-checks'),
  ('SUPER_ADMIN', 'task:cancel'),
  ('SUPER_ADMIN', 'comment:internal'),
  ('SUPER_ADMIN', 'client-update:publish'),
  ('SUPER_ADMIN', 'approval:manage'),
  ('SUPER_ADMIN', 'approval:decide'),
  ('SUPER_ADMIN', 'ticket:raise'),
  ('SUPER_ADMIN', 'ticket:read'),
  ('SUPER_ADMIN', 'ticket:triage'),
  ('SUPER_ADMIN', 'ticket:accept'),
  ('SUPER_ADMIN', 'ticket:escalate'),
  ('SUPER_ADMIN', 'ticket:reassign'),
  ('SUPER_ADMIN', 'ticket:resolve'),
  ('SUPER_ADMIN', 'ticket:reply-public'),
  ('SUPER_ADMIN', 'support-routing:manage'),
  ('SUPER_ADMIN', 'product:read'),
  ('SUPER_ADMIN', 'product:manage'),
  ('SUPER_ADMIN', 'sla:manage'),
  ('SUPER_ADMIN', 'qa:assign'),
  ('SUPER_ADMIN', 'qa:record-result'),
  ('SUPER_ADMIN', 'qa:verify-live'),
  ('SUPER_ADMIN', 'test-account:manage'),
  ('SUPER_ADMIN', 'test-credential:reveal'),
  ('SUPER_ADMIN', 'release:manage'),
  ('SUPER_ADMIN', 'release:approve'),
  ('SUPER_ADMIN', 'release:publish'),
  ('SUPER_ADMIN', 'uat:decide'),
  ('SUPER_ADMIN', 'github:manage'),
  ('SUPER_ADMIN', 'integration:read'),
  ('SUPER_ADMIN', 'integration:manage'),
  ('SUPER_ADMIN', 'repository:read'),
  ('SUPER_ADMIN', 'repository:manage'),
  ('SUPER_ADMIN', 'release-note:read'),
  ('SUPER_ADMIN', 'release-note:write'),
  ('SUPER_ADMIN', 'release-note:approve'),
  ('SUPER_ADMIN', 'release-note:publish'),
  ('SUPER_ADMIN', 'communication:manage'),
  ('SUPER_ADMIN', 'invoice:read'),
  ('SUPER_ADMIN', 'invoice:write'),
  ('SUPER_ADMIN', 'invoice:issue'),
  ('SUPER_ADMIN', 'invoice:void'),
  ('SUPER_ADMIN', 'payment:read'),
  ('SUPER_ADMIN', 'payment:record'),
  ('SUPER_ADMIN', 'ai-summary:read'),
  ('SUPER_ADMIN', 'ai-summary:generate'),
  ('SUPER_ADMIN', 'ai-summary:approve'),
  ('SUPER_ADMIN', 'problem:manage'),
  ('SUPER_ADMIN', 'problem:suggest-duplicate'),
  ('SUPER_ADMIN', 'rca:submit'),
  ('SUPER_ADMIN', 'incident:approve-emergency-fix'),
  ('SUPER_ADMIN', 'call:initiate'),
  ('SUPER_ADMIN', 'call:read-internal'),
  ('SUPER_ADMIN', 'call:play-recording'),
  ('SUPER_ADMIN', 'ivr:manage'),
  ('SUPER_ADMIN', 'report:read-own'),
  ('SUPER_ADMIN', 'report:read-team'),
  ('SUPER_ADMIN', 'report:read-all'),
  ('SUPER_ADMIN', 'report:export'),
  ('SUPER_ADMIN', 'cost:read'),
  ('PROJECT_MANAGER', 'project:read'),
  ('PROJECT_MANAGER', 'project:manage'),
  ('PROJECT_MANAGER', 'contract:read'),
  ('PROJECT_MANAGER', 'contract:manage'),
  ('PROJECT_MANAGER', 'contract:adjust-hours'),
  ('PROJECT_MANAGER', 'milestone:manage'),
  ('PROJECT_MANAGER', 'change-request:read'),
  ('PROJECT_MANAGER', 'change-request:raise'),
  ('PROJECT_MANAGER', 'change-request:manage'),
  ('PROJECT_MANAGER', 'task:read'),
  ('PROJECT_MANAGER', 'task:create'),
  ('PROJECT_MANAGER', 'task:assign'),
  ('PROJECT_MANAGER', 'task:work'),
  ('PROJECT_MANAGER', 'task:review'),
  ('PROJECT_MANAGER', 'task:override-checks'),
  ('PROJECT_MANAGER', 'task:cancel'),
  ('PROJECT_MANAGER', 'comment:internal'),
  ('PROJECT_MANAGER', 'client-update:publish'),
  ('PROJECT_MANAGER', 'approval:manage'),
  ('PROJECT_MANAGER', 'ticket:raise'),
  ('PROJECT_MANAGER', 'ticket:read'),
  ('PROJECT_MANAGER', 'ticket:triage'),
  ('PROJECT_MANAGER', 'ticket:accept'),
  ('PROJECT_MANAGER', 'ticket:escalate'),
  ('PROJECT_MANAGER', 'ticket:reassign'),
  ('PROJECT_MANAGER', 'ticket:resolve'),
  ('PROJECT_MANAGER', 'ticket:reply-public'),
  ('PROJECT_MANAGER', 'support-routing:manage'),
  ('PROJECT_MANAGER', 'product:read'),
  ('PROJECT_MANAGER', 'product:manage'),
  ('PROJECT_MANAGER', 'sla:manage'),
  ('PROJECT_MANAGER', 'qa:assign'),
  ('PROJECT_MANAGER', 'test-account:manage'),
  ('PROJECT_MANAGER', 'release:manage'),
  ('PROJECT_MANAGER', 'release:approve'),
  ('PROJECT_MANAGER', 'release:publish'),
  ('PROJECT_MANAGER', 'github:manage'),
  ('PROJECT_MANAGER', 'problem:manage'),
  ('PROJECT_MANAGER', 'incident:approve-emergency-fix'),
  ('PROJECT_MANAGER', 'call:initiate'),
  ('PROJECT_MANAGER', 'call:read-internal'),
  ('PROJECT_MANAGER', 'call:play-recording'),
  ('PROJECT_MANAGER', 'ivr:manage'),
  ('PROJECT_MANAGER', 'report:read-own'),
  ('PROJECT_MANAGER', 'report:read-team'),
  ('PROJECT_MANAGER', 'report:read-all'),
  ('PROJECT_MANAGER', 'report:export'),
  ('PROJECT_MANAGER', 'audit-log:read'),
  ('PROJECT_MANAGER', 'integration:read'),
  ('PROJECT_MANAGER', 'repository:read'),
  ('PROJECT_MANAGER', 'repository:manage'),
  ('PROJECT_MANAGER', 'release-note:read'),
  ('PROJECT_MANAGER', 'release-note:write'),
  ('PROJECT_MANAGER', 'release-note:approve'),
  ('PROJECT_MANAGER', 'release-note:publish'),
  ('PROJECT_MANAGER', 'invoice:read'),
  ('PROJECT_MANAGER', 'invoice:write'),
  ('PROJECT_MANAGER', 'invoice:issue'),
  ('PROJECT_MANAGER', 'payment:read'),
  ('PROJECT_MANAGER', 'payment:record'),
  ('PROJECT_MANAGER', 'ai-summary:read'),
  ('PROJECT_MANAGER', 'ai-summary:generate'),
  ('PROJECT_MANAGER', 'ai-summary:approve'),
  ('TEAM_LEAD', 'project:read'),
  ('TEAM_LEAD', 'project:manage'),
  ('TEAM_LEAD', 'contract:read'),
  ('TEAM_LEAD', 'milestone:manage'),
  ('TEAM_LEAD', 'change-request:read'),
  ('TEAM_LEAD', 'change-request:raise'),
  ('TEAM_LEAD', 'change-request:manage'),
  ('TEAM_LEAD', 'task:read'),
  ('TEAM_LEAD', 'task:create'),
  ('TEAM_LEAD', 'task:assign'),
  ('TEAM_LEAD', 'task:work'),
  ('TEAM_LEAD', 'task:review'),
  ('TEAM_LEAD', 'task:override-checks'),
  ('TEAM_LEAD', 'task:cancel'),
  ('TEAM_LEAD', 'comment:internal'),
  ('TEAM_LEAD', 'client-update:publish'),
  ('TEAM_LEAD', 'approval:manage'),
  ('TEAM_LEAD', 'ticket:raise'),
  ('TEAM_LEAD', 'ticket:read'),
  ('TEAM_LEAD', 'ticket:triage'),
  ('TEAM_LEAD', 'ticket:accept'),
  ('TEAM_LEAD', 'ticket:escalate'),
  ('TEAM_LEAD', 'ticket:reassign'),
  ('TEAM_LEAD', 'ticket:resolve'),
  ('TEAM_LEAD', 'ticket:reply-public'),
  ('TEAM_LEAD', 'support-routing:manage'),
  ('TEAM_LEAD', 'product:read'),
  ('TEAM_LEAD', 'qa:assign'),
  ('TEAM_LEAD', 'release:manage'),
  ('TEAM_LEAD', 'release:approve'),
  ('TEAM_LEAD', 'problem:manage'),
  ('TEAM_LEAD', 'rca:submit'),
  ('TEAM_LEAD', 'incident:approve-emergency-fix'),
  ('TEAM_LEAD', 'call:initiate'),
  ('TEAM_LEAD', 'call:read-internal'),
  ('TEAM_LEAD', 'call:play-recording'),
  ('TEAM_LEAD', 'report:read-own'),
  ('TEAM_LEAD', 'report:read-team'),
  ('TEAM_LEAD', 'report:export'),
  ('TEAM_LEAD', 'integration:read'),
  ('TEAM_LEAD', 'repository:read'),
  ('TEAM_LEAD', 'release-note:read'),
  ('TEAM_LEAD', 'release-note:write'),
  ('TEAM_LEAD', 'release-note:approve'),
  ('TEAM_LEAD', 'ai-summary:read'),
  ('TEAM_LEAD', 'ai-summary:generate'),
  ('TEAM_LEAD', 'ai-summary:approve'),
  ('DEVELOPER', 'project:read'),
  ('DEVELOPER', 'change-request:read'),
  ('DEVELOPER', 'task:read'),
  ('DEVELOPER', 'task:create'),
  ('DEVELOPER', 'task:work'),
  ('DEVELOPER', 'comment:internal'),
  ('DEVELOPER', 'ticket:raise'),
  ('DEVELOPER', 'ticket:read'),
  ('DEVELOPER', 'ticket:accept'),
  ('DEVELOPER', 'ticket:escalate'),
  ('DEVELOPER', 'ticket:reply-public'),
  ('DEVELOPER', 'qa:assign'),
  ('DEVELOPER', 'problem:suggest-duplicate'),
  ('DEVELOPER', 'rca:submit'),
  ('DEVELOPER', 'call:initiate'),
  ('DEVELOPER', 'call:read-internal'),
  ('DEVELOPER', 'report:read-own'),
  ('DEVELOPER', 'repository:read'),
  ('DEVELOPER', 'release-note:read'),
  ('DEVELOPER', 'ai-summary:read'),
  ('TESTER', 'project:read'),
  ('TESTER', 'change-request:read'),
  ('TESTER', 'task:read'),
  ('TESTER', 'task:create'),
  ('TESTER', 'task:work'),
  ('TESTER', 'comment:internal'),
  ('TESTER', 'ticket:raise'),
  ('TESTER', 'ticket:read'),
  ('TESTER', 'ticket:reply-public'),
  ('TESTER', 'qa:record-result'),
  ('TESTER', 'qa:verify-live'),
  ('TESTER', 'test-credential:reveal'),
  ('TESTER', 'release:approve'),
  ('TESTER', 'problem:suggest-duplicate'),
  ('TESTER', 'report:read-own'),
  ('TESTER', 'repository:read'),
  ('TESTER', 'release-note:read'),
  ('TESTER', 'ai-summary:read'),
  ('SUPPORT_EXECUTIVE', 'project:read'),
  ('SUPPORT_EXECUTIVE', 'contract:read'),
  ('SUPPORT_EXECUTIVE', 'change-request:read'),
  ('SUPPORT_EXECUTIVE', 'change-request:raise'),
  ('SUPPORT_EXECUTIVE', 'task:read'),
  ('SUPPORT_EXECUTIVE', 'task:create'),
  ('SUPPORT_EXECUTIVE', 'task:assign'),
  ('SUPPORT_EXECUTIVE', 'task:work'),
  ('SUPPORT_EXECUTIVE', 'comment:internal'),
  ('SUPPORT_EXECUTIVE', 'client-update:publish'),
  ('SUPPORT_EXECUTIVE', 'approval:manage'),
  ('SUPPORT_EXECUTIVE', 'ticket:raise'),
  ('SUPPORT_EXECUTIVE', 'ticket:read'),
  ('SUPPORT_EXECUTIVE', 'ticket:triage'),
  ('SUPPORT_EXECUTIVE', 'ticket:accept'),
  ('SUPPORT_EXECUTIVE', 'ticket:escalate'),
  ('SUPPORT_EXECUTIVE', 'ticket:reassign'),
  ('SUPPORT_EXECUTIVE', 'ticket:resolve'),
  ('SUPPORT_EXECUTIVE', 'ticket:reply-public'),
  ('SUPPORT_EXECUTIVE', 'product:read'),
  ('SUPPORT_EXECUTIVE', 'problem:manage'),
  ('SUPPORT_EXECUTIVE', 'call:initiate'),
  ('SUPPORT_EXECUTIVE', 'call:read-internal'),
  ('SUPPORT_EXECUTIVE', 'report:read-own'),
  ('INTERNAL_EMPLOYEE', 'ticket:raise'),
  ('INTERNAL_EMPLOYEE', 'ticket:read'),
  ('INTERNAL_EMPLOYEE', 'ticket:reply-public'),
  ('CLIENT_ADMIN', 'user:manage'),
  ('CLIENT_ADMIN', 'project:read'),
  ('CLIENT_ADMIN', 'contract:read'),
  ('CLIENT_ADMIN', 'change-request:read'),
  ('CLIENT_ADMIN', 'change-request:raise'),
  ('CLIENT_ADMIN', 'ticket:raise'),
  ('CLIENT_ADMIN', 'ticket:read'),
  ('CLIENT_ADMIN', 'ticket:reply-public'),
  ('CLIENT_ADMIN', 'approval:decide'),
  ('CLIENT_ADMIN', 'uat:decide'),
  ('CLIENT_ADMIN', 'report:read-own'),
  ('CLIENT_ADMIN', 'report:export'),
  ('CLIENT_EMPLOYEE', 'project:read'),
  ('CLIENT_EMPLOYEE', 'change-request:read'),
  ('CLIENT_EMPLOYEE', 'ticket:raise'),
  ('CLIENT_EMPLOYEE', 'ticket:read'),
  ('CLIENT_EMPLOYEE', 'ticket:reply-public')
) AS v(role_key, permission_key)
JOIN roles r
  ON r.key = v.role_key
 AND r.is_system = true
 AND r.organization_id IS NULL
 AND r.deleted_at IS NULL
JOIN permissions p
  ON p.key = v.permission_key
ON CONFLICT (role_id, permission_id) DO NOTHING;
